#!/bin/bash
#archivedir--Creates a compressed archive of the specified directory. Note: cd to the parent directory of the dir that
# you want to backup and then execute: archivedir DIRECTORY

# Size of a big directory in blocks.
maxarchivedir=10
compress=gzip
# Nicer format for error messages.
progname=$(basename "$0")
# Arguments required.
if [ $# -eq 0 ]; then
  echo "Usage: $progname directory" >&2
  exit 1
fi
if [ ! -d "$1" ]; then
  echo "${progname}: cannot find directory $1 to archive." >&2
  exit 1
fi
if [ "$(basename "$1")" != "$1" ] || [ "$1" = "." ]; then
  echo "${progname}: You must specify a subdirectory." >&2
  exit 1
fi
if [ ! -w . ]; then
  echo "${progname}: cannot write archive file to current directory." >&2
  exit 1
fi
# Check to see if the resultant archive is going to be dangerously big.
dirsize="$(du -s "$1" | awk '{print $1}')"
if [ "$dirsize" -gt $maxarchivedir ]; then
  /bin/echo -n "warning: directory $1 is $dirsize blocks. Proceed? [n] "
  # shellcheck disable=SC2162
  read answer
  answer="$(echo "$answer" | tr '[:upper:]' '[:lower:]' | cut -c1)"
  if [ "$answer" != "y" ]; then
    echo "${progname}: archive of directory $1 canceled." >&2
    exit 0
  fi
fi
archivename="$1.tgz"
if tar cf - "$1" | $compress > "$archivename" ; then
  echo "Directory $1 archived as $archivename"
else
  echo "warning: tar encountered errors archiving $1"
fi
exit 0
